services:
  moments:
    # build: . 
    build: .
    container_name: moments
    restart: always
    environment:
      PORT: 3000
      JWT_KEY: "test_secret_key" 
      
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
